SELECT H.NAME, H.HACKER_ID, CNT FROM 
HACKERS H 
JOIN 
(
    SELECT HACKER_ID ID, COUNT(CHALLENGE_ID) CNT
    FROM CHALLENGES
    GROUP BY ID
)
ON H.HACKER_ID = ID
ORDER BY CNT, 
HAVING CNT = MAX(CNT) OR 

/* incomplete */