SELECT  H.HACKER_ID,H.NAME
FROM HACKERS H 
JOIN 
(SELECT S.HACKER_ID AS ID, COUNT(*) AS CNT
 FROM 
 SUBMISSIONS S 
 JOIN CHALLENGES C 
    ON S.CHALLENGE_ID = C.CHALLENGE_ID 
 JOIN DIFFICULTY D 
    ON D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
 WHERE S.SCORE = D.SCORE 
 GROUP BY S.HACKER_ID
)
ON H.HACKER_ID = ID
WHERE CNT > 1
ORDER BY CNT DESC, H.HACKER_ID; 